title: Nat Hillard
author: Nat Hillard
description: "Engineer. Manager. Writer. Reader. "
show_downloads: false
google_analytics: UA-179825035-1
theme: jekyll-theme-minimal
logo:
github:
  is_user_page: true
  owner_name: Nat Hillard
  owner_url: http://github.com/nathillard/
social_links:
  twitter: anthillard
  github: nathillard
  facebook: nathillard
  instagram: hilloflard
  linkedin: nathillard
  medium: nathillard
  goodreads: https://www.goodreads.com/user/show/12688292-nat-hillard
