title: Nat Hillard
author: Nat Hillard
description: "Engineer. Manager. Writer. Reader. "
show_downloads: false
google_analytics: UA-179825035-1
theme: jekyll-theme-minimal
logo:
github:
  is_user_page: true
  owner_name: Nat Hillard
  owner_url: http://github.com/nathillard/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-font-awesome-sass
font-awesome:
  assets: true
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
exclude:
  - external
